### ISSUE TITLE
某书so版本

### ISSUE THREAD

**Issue by xbstory** [cuiqingandroid/frida-example#1]
请问xhs.js中用的so是对应哪个版本的app呢？谢谢～

**Comment by cuiqingandroid** [comment]
> 请问xhs.js中用的so是对应哪个版本的app呢？谢谢～

当时应该是6.4x，这个demo代码不涉及具体的so,主要思想是先hook `libart.so`,在关键函数拿到libshield.so的base addr.然后基于此hook ida里查看的函数的地址

**Comment by xbstory** [comment]
感谢回复
